import { useState } from "react";
import { createWorkflow } from "../api.js";
const emptyTask = () => ({ name: "", command: "" });
const emptyDependency = () => ({ upstream_task_name: "", downstream_task_name: "" });
export default function CreateWorkflowForm({ onCreated, onCancel }) {
  const [name, setName] = useState(""); const [tasks, setTasks] = useState([emptyTask()]); const [dependencies, setDependencies] = useState([]); const [error, setError] = useState(null); const [submitting, setSubmitting] = useState(false);
  function updateTask(index, field, value) { const next = [...tasks]; next[index][field] = value; setTasks(next); }
  function updateDependency(index, field, value) { const next = [...dependencies]; next[index][field] = value; setDependencies(next); }
  async function handleSubmit(e) { e.preventDefault(); setError(null); if (!name.trim()) return setError("Workflow name is required."); if (tasks.some((t) => !t.name.trim() || !t.command.trim())) return setError("Every task needs a name and a command."); setSubmitting(true); try { const payload = { name: name.trim(), tasks: tasks.map((t) => ({ name: t.name.trim(), command: t.command.trim() })), dependencies: dependencies.filter((d) => d.upstream_task_name && d.downstream_task_name).map((d) => ({ upstream_task_name: d.upstream_task_name.trim(), downstream_task_name: d.downstream_task_name.trim() })) }; const created = await createWorkflow(payload); onCreated(created.id); } catch (err) { setError(err.message); } finally { setSubmitting(false); } }
  return <div><button className="back-link" onClick={onCancel}>← All workflows</button><div className="create-heading"><p className="eyebrow">Build an automation</p><h1>New workflow</h1><p className="page-description">Define your tasks, then connect them into a reliable execution flow.</p></div><form onSubmit={handleSubmit} className="card create-form"><label>Workflow name</label><input value={name} onChange={(e) => setName(e.target.value)} placeholder="daily-etl-pipeline" /><div className="form-section-heading"><div><label>Tasks</label><p>Add each command your workflow should run.</p></div><span className="count-badge">{tasks.length}</span></div>{tasks.map((task, i) => <div key={i} className="input-row"><input placeholder="task name (e.g. extract)" value={task.name} onChange={(e) => updateTask(i, "name", e.target.value)} /><input placeholder="command (e.g. python extract.py)" value={task.command} onChange={(e) => updateTask(i, "command", e.target.value)} /><button type="button" onClick={() => setTasks(tasks.filter((_, idx) => idx !== i))} disabled={tasks.length === 1}>×</button></div>)}<button type="button" onClick={() => setTasks([...tasks, emptyTask()])}>+ Add task</button><div className="form-section-heading"><div><label>Dependencies <span>(optional)</span></label><p>Choose which task must finish before another starts.</p></div></div>{dependencies.map((dep, i) => <div key={i} className="input-row"><input placeholder="upstream task name" value={dep.upstream_task_name} onChange={(e) => updateDependency(i, "upstream_task_name", e.target.value)} /><input placeholder="downstream task name" value={dep.downstream_task_name} onChange={(e) => updateDependency(i, "downstream_task_name", e.target.value)} /><button type="button" onClick={() => setDependencies(dependencies.filter((_, idx) => idx !== i))}>×</button></div>)}<button type="button" onClick={() => setDependencies([...dependencies, emptyDependency()])}>+ Add dependency</button>{error && <p className="error-text">{error}</p>}<div className="form-actions"><button type="submit" className="primary" disabled={submitting}>{submitting ? "Creating…" : "Create workflow"}</button><button type="button" onClick={onCancel}>Cancel</button></div></form></div>;
}
