import { useEffect, useState } from "react";
import { getWorkflow, getWorkflowRuns } from "../api.js";
// Same fix as WorkflowList.jsx: `workflow.status` never existed (status
// lives on WorkflowRun, not Workflow). `null` here means "never run",
// which is distinct from any real WorkflowRunStatus value, so it gets
// its own class/label instead of defaulting to "pending". Individual
// WorkflowRun rows in the run-history list below DO have a real
// `status`, so this same function still applies to those correctly.
function statusClass(status) { if (!status) return "status-none"; const key = status.toLowerCase(); if (key.includes("success")) return "status-success"; if (key.includes("fail")) return "status-failed"; if (key.includes("partial")) return "status-partial"; if (key.includes("run")) return "status-running"; return "status-pending"; }
export default function WorkflowDetail({ workflowId, onBack }) {
  const [workflow, setWorkflow] = useState(null); const [runs, setRuns] = useState([]); const [error, setError] = useState(null); const [loading, setLoading] = useState(true);
  useEffect(() => { let cancelled = false; async function load() { setLoading(true); setError(null); try { const [wf, runData] = await Promise.all([getWorkflow(workflowId), getWorkflowRuns(workflowId).catch(() => [])]); if (!cancelled) { setWorkflow(wf); setRuns(runData); } } catch (err) { if (!cancelled) setError(err.message); } finally { if (!cancelled) setLoading(false); } } load(); return () => { cancelled = true; }; }, [workflowId]);
  return <div><button className="back-link" onClick={onBack}>← All workflows</button>{loading && <div className="loading-state"><span className="spinner" />Loading workflow</div>}{error && <p className="error-text">{error}</p>}{workflow && <><div className="detail-hero"><div><p className="eyebrow">Workflow overview</p><h1>{workflow.name}</h1><p className="page-description">A coordinated sequence of tasks and dependencies.</p></div><span className={`status-pill ${statusClass(workflow.latest_run_status)}`}>{workflow.latest_run_status || "No runs yet"}</span></div><section className="content-section"><div className="section-heading"><div><p className="eyebrow">Execution plan</p><h2>Tasks</h2></div><span className="count-badge">{(workflow.tasks || []).length}</span></div><div className="task-list">{(workflow.tasks || []).map((task, index) => <div key={task.id} className="card task-card"><div className="task-number">{String(index + 1).padStart(2, "0")}</div><div><div className="task-name">{task.name}</div><code>{task.command}</code></div></div>)}</div></section><section className="content-section"><div className="section-heading"><div><p className="eyebrow">Task relationships</p><h2>Dependencies</h2></div></div>{(workflow.dependencies || []).length === 0 ? <div className="subtle-empty">No dependencies — tasks run independently.</div> : <div className="dependency-list">{workflow.dependencies.map((dep, i) => <div key={i} className="card dependency-card"><span>{dep.upstream_task_id}</span><b>→</b><span>{dep.downstream_task_id}</span></div>)}</div>}</section><section className="content-section"><div className="section-heading"><div><p className="eyebrow">Activity</p><h2>Run history</h2></div></div>{runs.length === 0 ? <div className="subtle-empty">No runs have been recorded yet.</div> : runs.map((run) => <div key={run.id} className="card workflow-row"><div><div className="workflow-name">Run #{run.id}</div><div className="muted">{run.triggered_at || run.created_at}</div></div><span className={`status-pill ${statusClass(run.status)}`}>{run.status || "pending"}</span></div>)}</section></>}</div>;
}
